### ISSUE TITLE
Action throws deprecation warning

### ISSUE THREAD

**Issue by s-weigand** [percy/snapshot-action#14]
Recently this action started giving the following deprecation warning.
```
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

This can be solved by using `@actions/core=^1.2.6` (see #13 ) + rebundeling and releasing the action.
> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.

**Comment by s-weigand** [comment]
Resolved, thanks a lot 😄

**Comment by Robdel12** [comment]
Sorry for the slow turn around on it! Happy to get out out in any case :)
