### ISSUE TITLE
Change usage guide version to master

### ISSUE THREAD

**Issue by s-weigand** [percy/snapshot-action#2]
Just started adapting to this action (@Robdel12 thanks for the pointer here) and it promptly fails since I used `uses: percy/snapshot-action@v0.1.0` from the example and there is no release yet. My suggestion would be to use `uses: percy/snapshot-action@master` for the time being.

PS: To automate minor and major version releases [this action](https://github.com/technote-space/release-github-actions) works like a charm.

**Comment by Robdel12** [comment]
Nice, thanks for the auto release action. Looks great. 😃 

This action isn't quite released yet (just spun this repo up late last night). I'm going to close this up since I'll be releasing in the next hour or so 👍
