### ISSUE TITLE
Wrong branch name for PR

### ISSUE THREAD

**Issue by s-weigand** [percy/snapshot-action#3]
The branch name for a PR isn't the name of the actual branch, but `<PR-number>/merge`.

**Comment by Robdel12** [comment]
This action isn't released yet. #1 Will fix it

**Comment by s-weigand** [comment]
Just wanted to let you know :smile:

**Comment by Robdel12** [comment]
Heh, yeah, we found out over here: https://github.com/percy/example-percy-jekyll/pull/12
