### ISSUE TITLE
Javascript vs Ruby

### ISSUE THREAD

**Issue by jasikpark** [percy/snapshot-action#8]
This takes a full minute longer to run than the cli does on Netlify.

Percy Agent is **much** slower than the original cli.

**Comment by Robdel12** [comment]
Hey Caleb! That's correct, the old CLI would only upload the assets to the API, where the browsers would render the page directly. The new CLI opens a puppeteer browser, iterates through the static files, and captures DOM snapshots (fully rendered pages). This is inline with how all our other SDKs function. 

You're free to keep using the old Ruby CLI 👍

**Comment by jasikpark** [comment]
Is there any functional difference between the data they capture?

Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz

**Comment by Robdel12** [comment]
Yeah, the new SDK will capture fully rendered DOM with JS enabled when going taking snapshots. The old Ruby SDK just uploaded the HTML and then rendered that as is in our browsers

**Comment by jasikpark** [comment]
Ok, I see now -- it's moving the time from y'all's service to the actual CI service -- resulting in about the same amount of time till it's done.
